name: test

on:
  pull_request:
    branches: [ backend/dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run Jest tests
      run: npm test
      env:
        MONGO_URI: ${{secrets.MONGO_URI}}
        TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}